// MARK: - ResponseMapping
//
// Auto-generated by scripts/generate-response-mapping.swift
// DO NOT EDIT THIS FILE MANUALLY.
//
// To regenerate, run from the repository root:
//   swift scripts/generate-response-mapping.swift
//
// Maps OpenAPI-generated Output enums to the unified ResponseCase type.
// Each extension converts operation-specific cases into a common shape,
// eliminating repetitive switch boilerplate in KaitenClient methods.

// MARK: - Cards

extension Operations.get_cards.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_cards.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_card.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_card.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_card.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_card.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_card.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.batch_update_cards.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.batch_update_cards.Output.Accepted.Body> {
    switch self {
    case .accepted(let accepted): .ok(accepted.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Members & Comments

extension Operations.retrieve_list_of_card_members.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.retrieve_list_of_card_members.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_card_member.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_card_member.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card_member_role.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_card_member_role.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_card_member.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_card_member.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.retrieve_card_comments.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.retrieve_card_comments.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_card_comment.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_card_comment.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card_comment.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_card_comment.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Checklists

extension Operations.create_checklist.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_checklist.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_checklist.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_checklist.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_card.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_card.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_card_comment.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_card_comment.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_checklist.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_checklist.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_checklist.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_checklist.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Checklist Items

extension Operations.create_checklist_item.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_checklist_item.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_checklist_item.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_checklist_item.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_checklist_item.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_checklist_item.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_item_to_checklist.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_item_to_checklist.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_item_in_checklist.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_item_in_checklist.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_item_from_checklist.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_item_from_checklist.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Custom Properties

extension Operations.get_list_of_properties.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_properties.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_property.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_property.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_property.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_property.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_property.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_property.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_property.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_property.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_list_of_select_values.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_select_values.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_select_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_select_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_select_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_select_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_select_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_select_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_select_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_select_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_list_of_vote_values.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_vote_values.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_vote_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_vote_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_vote_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_vote_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_vote_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_vote_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Custom Property Catalog Values

extension Operations.get_list_of_catalog_values.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_catalog_values.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_catalog_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_catalog_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_catalog_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_catalog_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_catalog_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_catalog_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_catalog_value.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_catalog_value.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Boards

extension Operations.get_board.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_board.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_list_of_columns.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_columns.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_list_of_lanes.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_lanes.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Spaces

extension Operations.retrieve_list_of_spaces.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.retrieve_list_of_spaces.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_list_of_boards.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_boards.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Tags

extension Operations.list_card_children.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_card_children.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_card_child.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_card_child.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_card_child.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_card_child.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.list_card_tags.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_card_tags.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_card_tag.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_card_tag.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_card_tag.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_card_tag.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Users

extension Operations.retrieve_list_of_users.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.retrieve_list_of_users.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.retrieve_current_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.retrieve_current_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Blockers

extension Operations.list_card_blockers.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_card_blockers.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_card_blocker.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_card_blocker.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card_blocker.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_card_blocker.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_card_blocker.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_card_blocker.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Types

extension Operations.list_card_types.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_card_types.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_card_type.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_card_type.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_card_type.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_card_type.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card_type.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_card_type.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_card_type.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_card_type.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Sprints

extension Operations.list_sprints.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_sprints.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - External Links

extension Operations.list_card_external_links.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_card_external_links.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_card_external_link.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_card_external_link.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card_external_link.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_card_external_link.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_card_external_link.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_card_external_link.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Location History

extension Operations.get_card_location_history.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_card_location_history.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Sprint Summary

extension Operations.get_sprint_summary.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_sprint_summary.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Spaces CRUD

extension Operations.create_space.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_space.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.retrieve_space.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.retrieve_space.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_space.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_space.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Boards CRUD

extension Operations.create_board.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_board.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_board.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_board.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Columns CRUD

extension Operations.create_column.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_column.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_column.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_column.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_column.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_column.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Subcolumns

extension Operations.get_list_of_subcolumns.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_list_of_subcolumns.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_subcolumn.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_subcolumn.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_subcolumn.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_subcolumn.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_subcolumn.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_subcolumn.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Lanes CRUD

extension Operations.create_lane.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_lane.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_lane.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_lane.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Baselines

extension Operations.get_card_baselines.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_card_baselines.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card SLA

extension Operations.get_card_sla_measurements.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_card_sla_measurements.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Files

extension Operations.attach_file_to_card.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.attach_file_to_card.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .serviceUnavailable: .undocumented(statusCode: 503)
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card_file.Output {
  func toCase() -> KaitenClient.ResponseCase<Void> {
    switch self {
    case .ok: .ok(())
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.detach_file_from_card.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.detach_file_from_card.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Automations

extension Operations.list_automations.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_automations.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_automation.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_automation.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_automation.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_automation.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_automation.Output {
  func toCase() -> KaitenClient.ResponseCase<Void> {
    switch self {
    case .ok: .ok(())
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Space Users

extension Operations.list_space_users.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_space_users.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.invite_user_to_space.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.invite_user_to_space.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_space_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_space_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_space_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_space_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_space_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_space_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .conflict: .undocumented(statusCode: 409)
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Service Desk External Recipients

extension Operations.add_sd_external_recipient.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_sd_external_recipient.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_sd_external_recipient.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_sd_external_recipient.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Service Desk Services

extension Operations.list_service_desk_services.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_service_desk_services.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Blocker Categories

extension Operations.list_blocker_categories.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_blocker_categories.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_blocker_category.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_blocker_category.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_blocker_category.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_blocker_category.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Type Tree Entities

extension Operations.list_card_type_tree_entities.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_card_type_tree_entities.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_card_type_tree_entity.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_card_type_tree_entity.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_card_type_tree_entity.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_card_type_tree_entity.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Allowed Users

extension Operations.retrieve_card_allowed_users.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.retrieve_card_allowed_users.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Time Logs

extension Operations.get_card_time_logs.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_card_time_logs.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_card_time_log.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_card_time_log.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_card_time_log.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_card_time_log.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_card_time_log.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_card_time_log.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Audit Logs

extension Operations.retrieve_audit_log_events.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.retrieve_audit_log_events.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Card Blocker Users

extension Operations.list_card_blocker_users.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_card_blocker_users.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_card_blocker_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_card_blocker_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_card_blocker_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_card_blocker_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.retrieve_current_user_blockers.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.retrieve_current_user_blockers.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Checklist Cards

extension Operations.retrieve_cards_with_checklist.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.retrieve_cards_with_checklist.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Custom Directories

extension Operations.list_custom_directories.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_custom_directories.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_custom_directory.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_custom_directory.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_custom_directory.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_custom_directory.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_custom_directory.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_custom_directory.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_custom_directory.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_custom_directory.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Company Users

extension Operations.get_company_users.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_company_users.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_company_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_company_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_virtual_user.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_virtual_user.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Custom Directory Fields

extension Operations.list_custom_directory_fields.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_custom_directory_fields.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_custom_directory_field.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.create_custom_directory_field.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_custom_directory_field.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_custom_directory_field.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_custom_directory_field.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.update_custom_directory_field.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_custom_directory_field.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.delete_custom_directory_field.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Custom Directory Records

extension Operations.list_custom_directory_records.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.list_custom_directory_records.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_custom_directory_record.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.create_custom_directory_record.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_custom_directory_record.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_custom_directory_record.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_custom_directory_record.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.update_custom_directory_record.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_custom_directory_record.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.delete_custom_directory_record.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.list_custom_directory_record_cards.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.list_custom_directory_record_cards.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Custom Property Tree Entities

extension Operations.list_custom_property_tree_entities.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.list_custom_property_tree_entities.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_custom_property_tree_entity.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.add_custom_property_tree_entity.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_custom_property_tree_entity.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.delete_custom_property_tree_entity.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Group Admins

extension Operations.list_group_admins.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_group_admins.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_group_admin.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_group_admin.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_group_admin.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_group_admin.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Document Schemas

extension Operations.get_document_schema.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_document_schema.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Group Entities

extension Operations.list_group_entities.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_group_entities.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_group_entity.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_group_entity.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_group_entity.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_group_entity.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_group_entity.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_group_entity.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Custom Property Collective Score Values

extension Operations.get_list_of_collective_score_values.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.get_list_of_collective_score_values.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_collective_score_value.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.create_collective_score_value.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_collective_score_value.Output {
  func toCase()
    -> KaitenClient.ResponseCase<Operations.update_collective_score_value.Output.Ok.Body>
  {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Group Users

extension Operations.list_group_users.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_group_users.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.add_user_to_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.add_user_to_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_user_from_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_user_from_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Document Groups

extension Operations.list_document_groups.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_document_groups.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_document_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_document_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .conflict: .undocumented(statusCode: 409)
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_document_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_document_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_document_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_document_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .conflict: .undocumented(statusCode: 409)
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.delete_document_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.delete_document_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

// MARK: - Groups

extension Operations.list_groups.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.list_groups.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.create_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.create_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.get_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.get_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.update_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.update_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .badRequest: .undocumented(statusCode: 400)
    case .unauthorized: .unauthorized
    case .code402: .undocumented(statusCode: 402)
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}

extension Operations.remove_group.Output {
  func toCase() -> KaitenClient.ResponseCase<Operations.remove_group.Output.Ok.Body> {
    switch self {
    case .ok(let ok): .ok(ok.body)
    case .unauthorized: .unauthorized
    case .forbidden: .forbidden
    case .notFound: .notFound
    case .undocumented(statusCode: let code, _): .undocumented(statusCode: code)
    }
  }
}
